# Generated by Django 4.2.5 on 2023-09-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machin',
            new_name='User',
        ),
    ]
