# Generated by Django 4.2.5 on 2023-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='count',
            field=models.IntegerField(),
        ),
    ]
