version: "3.9"

services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations && 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:7000"
    ports:
      - "7000:7000"
    env_file:
      - .env
    volumes:
      - .:/project
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

volumes:
  postgres_data:
