apiVersion: v1
kind: Secret
metadata:
    name: app-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: cG9zdGdyZXM=
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLSpiXjFsaTAteiF4bnNmXyhqOHI2JCstbjRyYl55Zi0tK3N5aCMjYnVtejkqZHB1aGFv