apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: django
          image: salydgn/django:latest   
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: SECRET_KEY

            - name: ALLOWED_HOST
              valueFrom: 
                configMapKeyRef:
                  name: app-configmap
                  key: ALLOWED_HOSTS


            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: POSTGRES_DB

            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: POSTGRES_PORT
          args:
            - sh
            - -c
            - "python manage.py makemigrations && \n      python manage.py migrate &&\n
              \     python manage.py runserver 0.0.0.0:8000"

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: my-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
