apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: django
          image: salydgn/django:latest   
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              value: django-insecure-*b^1li0-z!xnsf_(j8r6$+-n4rb^yf--+syh##bumz9*dpuhao
            - name: ALLOWED_HOST
              value: "*"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: my-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
