name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install psycopg2 dependencies
      run: |
        sudo apt-get install libpq-dev -y
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check the formatting
      uses: rickstaa/action-black@v1
      with:
          black_args: ". --check"

    - name: Check the linting
      run: ruff check .
      
    - name: Run Tests
      run: |
        python manage.py test

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}:latest
      

        
    
